#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/liteti-remote/rustdesk /usr/bin/liteti-remote

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/liteti-remote.service ]; then
			rm /etc/systemd/system/liteti-remote.service /usr/lib/systemd/system/liteti-remote.service /usr/lib/systemd/user/liteti-remote.service >/dev/null  2>&1 || true
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/liteti-remote/files/systemd/liteti-remote.service /usr/lib/systemd/system/liteti-remote.service
		# try fix error in Ubuntu 18.04
		# Failed to reload rustdesk.service: Unit rustdesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/rustdesk.service:10: Executable path is not absolute: pkill -f "rustdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/liteti-remote.service
		fi
		systemctl daemon-reload
		systemctl enable liteti-remote
		systemctl start liteti-remote
	fi
fi
